[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["python"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
serviceName = "nmtc-backend"